### ISSUE TITLE
Running STAR with GTF provided on the fly

### ISSUE THREAD

**Issue by kopardev** [skchronicles/RNA-seek#1]
I have some scripts doing this here `/scratch/kopardevn/fasta_GTF_testing/scripts`:

- `make_star_index.sh` creates the STAR index with just the fasta file. This is all you need going forward
- `star1p_pipeliner_version.sh` and `star2p_pipeliner_version.sh` have code to calculate the _mean read length_ and use _mean read length minus 1_ as the overhang
- GTF file is directly provided to `star1p_pipeliner_version.sh` and `star2p_pipeliner_version.sh` at runtime. The whole idea is that when Gencode roles out a new GTF, we can switch to the new GTF seamlessly
- `--outTmpDir` uses `/lscratch` to make things faster... you can also try with `/dev/shm`

**Comment by kopardev** [comment]
Copied over the files to `/data/CCBR/dev/RNA-seek/tmp`

**Comment by skchronicles** [comment]
### Updates 

#### Commit f7e19719c16e5257e8c630972a938fafd9d4180b partially resolves this issue. It is using this method to run STAR.


These new STAR Indices are built without providing an annotation or sjdbOverhang. This adds a little extra runtime but saves a lot of disk space. The parameter _sjdbOverhang_ is calculated during runtime: `sjdbOverhang = max(read length) - 1`. If _sjdbOverhang_ cannot be determined or the read length is less than 100 bp, it will default to 100. 

We could use the same docker image that arriba is using. It includes STAR/2.7.6a, Arriba, Samtools, Picard, Samblaster. We should probably move to the latest version of STAR to match Arriba. I will just need to update the existing STAR rules to use the annotation-free STAR reference and update the shell commands.

**Comment by skchronicles** [comment]
### DONE

Commit 996b00dc8b18186c81ff8eea6d09dae53af0a279 resolves this issue.

`rna-seek build` now generates a GENOMIC FASTA Index for STAR and Arriba, and STAR 2-pass now uses the pre-built genomic index instead of the pre-built sjdbOverhang + GTF index. I have also moved to **STAR/2.7.6a instead of STAR/2.7.0f** to match Arriba and to use a consistent version throughout the pipeline.
