### ISSUE TITLE
RNA-seek Documentation

### ISSUE THREAD

**Issue by kopardev** [skchronicles/RNA-seek#21]
- create a new json (or yaml) file in the workdir listing all tools used by the pipeline along with their version numbers

**Comment by skchronicles** [comment]
Would this be better placed within RNA-seek's documentation? That is still on the TODO list but I was planning on creating some offical documentation when version 1.0.0 has been released.

**Comment by skchronicles** [comment]
## Resolved

Please see the resources page for RNA-seek for more information about each tool and docker image the pipeline employs:
https://ccbr.github.io/RNA-seek/RNA-seq/Resources/
