### ISSUE TITLE
Running the pipeline other than Biowulf

### ISSUE THREAD

**Issue by erenada** [skchronicles/RNA-seek#27]
Hello,

Is it possible to run this pipeline in other clusters/computers (perhaps via Singularity or Docker version)?

Thank you!

**Comment by skchronicles** [comment]
Hey @erenada,

I hope all is going well on your side! Yes, if you have access to a SLURM cluster, setup/installtion of the pipeline should be pretty easy. 

When ever you have some free time, can you provide me some more information about where you plan on running the pipeline (job scheduler, is singularity installed, is snakemake installed, etc.)? 

Best Regards,
@skchronicles

**Comment by erenada** [comment]
Hello Skyler, 

Thank you, it's all good here - I hope you are doing well too! And thank you for getting back to my question.

I was trying to run this pipeline in [a SLURM cluster](https://harvardmed.atlassian.net/wiki/spaces/O2/overview?homepageId=1586790623), however couldn't make it work.

I have installed snakemake and singularity through conda (also paths are added to the .bash_profile). When I try to run a test (using flag --mode local) it starts to pull singularity image dockers (fastqc, picard etc.); but then it stops. 

When I check back the snakemake.log, I see this error: 

rule validator:
    input: /home/era444/RNA-seek/output/KO_S4.R1.fastq.gz, /home/era444/RNA-seek/output/KO_S4.R2.fastq.gz
    output: /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R1.fastq.log, /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R2.fastq.log
    jobid: 2
    reason: Missing output files: /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R1.fastq.log, /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R2.fastq.log
    wildcards: name=KO_S4
    priority: 2
    resources: tmpdir=/tmp

    mkdir -p /home/era444/RNA-seek/output/rawQC
    fastQValidator --noeof --file /home/era444/RNA-seek/output/KO_S4.R1.fastq.gz > /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R1.fastq.log
    fastQValidator --noeof --file /home/era444/RNA-seek/output/KO_S4.R2.fastq.gz > /home/era444/RNA-seek/output/rawQC/KO_S4.validated.R2.fastq.log

Activating singularity image /home/era444/RNA-seek/output/.snakemake/singularity/0eb7bee9073f23390c63016bf54e6eaa.simg

FATAL:   apptainer image is not in an allowed configured path

It's seems like a path and/or permission related issue but not sure where it originates.


The other thing I noticed in the genome config files that is most of the reference genome files are local (for eg: "GENOME": "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg38_30/ref.fa").

I am not yet in that step but I worried that this could also a problem too. I tried to create these files locally via 'rna-seek build' command, but then it wants to submit a slurm job - which gives me errors due to different flags in slurm job submission. I thought it would be way easier to run whole pipeline if those files were on s3. 

Any help/suggestion is greatly appreciated, thank you so much!

All best,
Eren

**Comment by skchronicles** [comment]
Hey Eren,

Do you know if singularity/apptainer has already been installed by a sysadmin? Singularity should really be installed by HPC administrator as there may be some features that you cannot enable as a regular user. Would it be possible to meet sometime next week to look into this more? If you can email me, I can set up a MS Teams meeting whenever you have some free time.

Please let me know what you think.

Best regards,
@skchronicles

**Comment by skchronicles** [comment]
I am just following up on this thread, just in case another user runs into the same problem. I met with @erenada to get more information about some of the issues he experienced while installing the pipeline at a Havard Medical School cluster.

Concerning the following error message, `FATAL:   apptainer image is not in an allowed configured path`, it looks like the developers of apptainer have imposed some restrictions on where SIFs can be installed/executed.  There is some discussion [here](https://github.com/apptainer/singularity/issues/458) about that subject. To overcome this issue, I would highly recommend that singularity/apptainer is installed by an HPC staff member or sysadmin.  The default conf file has restrictions as to where SIFs can be executed from on the file system.

Here is one other issue we encountered while running the cache sub-command. On the HMS cluster, the `-p PARTITION` option is required with sbatch. To overcome this issue, an alias for sbatch was created:
```bash
alias sbatch='sbatch -p PARTITION_NAME'
```

Also, for submission of jobs in the `rna-seek run` pipeline, the partition name in the cluster.json file should be [edited to the name of your partition](https://github.com/skchronicles/RNA-seek/blob/e46cda63bb7ea71742bd54717ff426ccdc9047d6/resources/cluster.json#L5). So, replace `norm` with the name of your partition.

**Comment by skchronicles** [comment]
@erenada I am going to close this issue for now. If you run into any other problems, feel free to email or reach out here!
